//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFix.Regedit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFix.Regedit.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\1394ohci]
        ///&quot;ImagePath&quot;=hex(2):5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,\
        ///&quot;Start&quot;=dword:00000003
        ///&quot;ErrorControl&quot;=dword:00000001
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\3ware]
        ///&quot;ImagePath&quot;=hex(2):53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,64,00,\
        ///&quot;Start&quot;=dword:00000000
        ///&quot;ErrorControl&quot;=dword:00000001
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AarSvc]
        ///&quot;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string service_defaults_2004_19041_450 {
            get {
                return ResourceManager.GetString("service_defaults_2004_19041_450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\takeownership]
        ///@=&quot;Take ownership&quot;
        ///&quot;HasLUAShield&quot;=&quot;&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\takeownership\command]
        ///@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; /d Y &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F /c&quot;
        ///&quot;IsolatedCommand&quot;=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; /d Y &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F /c&quot;
        ///
        ///
        ///[HKEY_CLASSES_ROOT\Directory\shell\takeownership]
        ///@=&quot;Take ownership&quot;
        ///&quot;HasLUAShield&quot;=&quot;&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TakeOwnership_add {
            get {
                return ResourceManager.GetString("TakeOwnership_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[-HKEY_CLASSES_ROOT\*\shell\takeownership]
        ///[-HKEY_CLASSES_ROOT\Directory\shell\takeownership]
        ///.
        /// </summary>
        internal static string TakeOwnership_remove {
            get {
                return ResourceManager.GetString("TakeOwnership_remove", resourceCulture);
            }
        }
    }
}
